FROM nginx:1.24
RUN rm -rf /usr/share/nginx/html/index.html
RUN rm -rf /etc/nginx/conf.d/default.conf
RUN rm -rf /etc/nginx/nginx.conf
COPY static/* /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf
