FROM maven 
WORKDIR /opt/server
COPY static/src .
RUN mvn clean package
RUN mv target/shipping-1.0.jar /opt/server/shipping.jar
ENV CART_ENDPOINT=cart:8080 \
    DB_HOST="mysql"
CMD ["java", "-jar", "shipping.jar"]